os: osx
osx_image: xcode14.2
language: swift
script: 
  - xcodebuild clean build test -project ./EssentialFeed.xcodeproj -scheme "CI_macOS" -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
  - xcodebuild clean build test -project ./EssentialFeed.xcodeproj -scheme "CI_iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro" ONLY_ACTIVE_ARCH=YES